project:
  type: website
  output-dir: _site
  render: [docs]

website:
  title: "Synoetic OS: Research Hub"
  site-path: "/synoeticos-public/"
  navbar:
    background: "#131B2C"
    foreground: "#F9C84A"
    left:
      - href: docs/index.md
        text: Home
      - href: docs/elevation-grid/index.md
        text: Elevation Grid