theme: jekyll-theme-minimal
title: Synoetic OS Whitepapers
description: A collection of whitepapers and research on Synoetic OS.
huggingface: https://huggingface.co/Feirbrand/
spaces: https://huggingface.co/Feirbrand/spaces